#Application Configuration
server:
  port: 8091

security:
  basic:
    enable: false
  ignored: /**

# To See H2 Console in Browser:
# http://localhost:8091/h2-console
# Enabling H2 Console
spring:
  h2:
    console:
      enabled: true
    # ===============================
    # DB
    # ===============================
    # url: jdbc:h2:mem:productDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    # driverClassName: org.h2.Driver
  datasource:
    url: jdbc:sqlserver://localhost;database=mutante;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: 123456.123

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    show-sql: true
   # hibernate:
   #   ddl-auto: update
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
  sql:
    init:
      platform: mssql
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
my:
  url:
    palatsi: "https://f3e753d36a1a0df08e8d6017ab9c9801:1ae378481a17be9c07893adba022f366@palatsi-com-co.myshopify.com/admin/api/2019-10/products/"
    dolphin: "dsds"
    ellence: ""
    pass_palatsi: "1ae378481a17be9c07893adba022f366"
    pass_dolphin: "1ae378481a17be9c07893adba022f366"
    pass_ellence: "1ae378481a17be9c07893adba022f366"

